export interface IShopowner {
    Name: string,
    password: string,
    email: string,
    role: string,
    Adresse: string,
    adresseFacturation: string,
    codeTVA: string,
    NumTel: string,
    PaymentMethode: string,
    matriculeFiscale : string,
    commission: string,
    delaiPayement: string,
    walletpublickey:string,
  }